name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Group 6 CWork!
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn package  # This packages the project into a JAR
      - name: Build Docker Image
        run: docker build -t semimage .
      - name: Run image
        run: docker run --name semcontainer -d semimage
      - name: View logs
        run: docker logs semcontainer
